from sqlalchemy import (
    Column,
    Integer,
    String,
    Float,
    DateTime,
    Text,
    Boolean,
    DECIMAL
)
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.sql import func

Base = declarative_base()

class Supplier1(Base):
    __tablename__ = "supplier_1"

    articelno = Column(String(255), primary_key=True)  # Chave primária
    description = Column(Text, nullable=False)
    quantity = Column(Integer, nullable=False)
    sellingprice = Column(Float, nullable=False)
    manufacturer = Column(String(255), nullable=False)
    ean = Column(String(255), unique=True, nullable=False)
    category = Column(String(255), nullable=True)
    image = Column(Text, nullable=True)
    suppoints = Column(Integer, default=0)
    next_delivery_amount = Column(Integer, default=0)
    next_delivery_date = Column(String(255), nullable=True)
    part_number = Column(String(255), nullable=True)

class Item(Base):
    __tablename__ = "items"

    id = Column(Integer, primary_key=True, index=True) # Chave primária
    title = Column(String(255), nullable=True)
    ean = Column(String(255), unique=True, nullable=False)
    stock = Column(Integer, nullable=True)
    price = Column(DECIMAL(10,2), nullable=True)
    pvpr = Column(DECIMAL(10,2), nullable=True)
    img = Column(Text, nullable=True)
    brand = Column(String(255), nullable=True)
    last_updated = Column(DateTime(timezone=True), nullable=True)
    color = Column(String(255), nullable=True)
    category = Column(String(255), nullable=True)
    img_updated = Column(DateTime(timezone=True), nullable=True)
    keywords = Column(String(255), nullable=True)
    family = Column(String(255), nullable=True)
    subfamily = Column(String(255), nullable=True)
    activated = Column(Integer, nullable=False, default=1)
    created_at = Column(DateTime, nullable=False, default=func.now())
    supplier = Column(String(255), nullable=False, default="unknown")
    blocopt = Column(Text, nullable=True)
    blocogb = Column(Text, nullable=True)
    img_failures = Column(Integer, default=0)
    size = Column(Text, nullable=True)
    age = Column(Text, nullable=True)
    subcategory = Column(Text, nullable=True)

    @property
    def price_b2c(self):
        if self.price is not None:
            return round(self.price * 1.26, 2)
        return None

    @property
    def price_b2b(self):
        if self.price is not None:
            return round(self.price * 1.08, 2)
        return None

class ImportCSV(Base):
    __tablename__ = "yollgo"

    ean = Column(String(255), primary_key=True) # Chave primária
    brand = Column(String(255), nullable=False)
    title = Column(String(255), nullable=False)
    color = Column(String(255), nullable=True)
    category = Column(String(255), nullable=True)
    family = Column(String(255), nullable=True)
    subfamily = Column(String(255), nullable=True)
    price = Column(Float, nullable=True)
    stock = Column(Integer, nullable=False)
    supplier = Column(String(255), nullable=False)
    img = Column(String(255), nullable=True)
    pvpr = Column(Float, nullable=True, default=0)
    created_at = Column(DateTime, nullable=True, default=func.now())
    blocopt = Column(Text, nullable=True)
    blocogb = Column(Text, nullable=True)
    size = Column(Text, nullable=True)
    age = Column(Text, nullable=True)
    subcategory = Column(Text, nullable=True)
    keywords = Column(Text, nullable=True)


# Tabela Redicom Stock
class B2BStock(Base):
    __tablename__ = "b2b_stock"

    id = Column(Integer, primary_key=True) # Chave primária
    ordem = Column(Integer, nullable=True)
    nomept = Column(Text, nullable=True)
    categoria = Column(Integer, nullable=True)
    subcategoria = Column(Integer, nullable=True)
    nomegb = Column(Text, nullable=True)
    descpt = Column(Text, nullable=True)
    descgb = Column(Text, nullable=True)
    sku = Column(Text, nullable=True)
    sku_family = Column(Text, nullable=True)
    sku_group = Column(Text, nullable=True)
    activo = Column(Integer, nullable=True, default=0)
    blocopt = Column(Text, nullable=True)
    descritorespt = Column(Text, nullable=True)
    blocogb = Column(Text, nullable=True)
    descritoresgb = Column(Text, nullable=True)
    seo_titulopt = Column(Text, nullable=True)
    seo_descpt = Column(Text, nullable=True)
    seo_titulogb = Column(Text, nullable=True)
    seo_descgb = Column(Text, nullable=True)
    cor = Column(Text, nullable=True)
    tamanho = Column(Text, nullable=True)
    familia = Column(Text, nullable=True)
    subfamilia = Column(Text, nullable=True)
    gama = Column(Integer, nullable=True)
    see_also = Column(Text, nullable=True)
    tags = Column(Text, nullable=True)
    tecs = Column(Text, nullable=True)
    cuidados = Column(Text, nullable=True)
    novidade = Column(Boolean, nullable=True)
    destaque = Column(Boolean, nullable=True)
    marca = Column(Text, nullable=True)
    ano = Column(Integer, nullable=True)
    genero = Column(Integer, nullable=True)
    semestre = Column(Integer, nullable=True)
    generico1 = Column(Text, nullable=True)
    generico2 = Column(Text, nullable=True)
    generico3 = Column(Text, nullable=True)
    nomesp = Column(Text, nullable=True)
    descsp = Column(Text, nullable=True)
    blocosp = Column(Text, nullable=True)
    nomefr = Column(Text, nullable=True)
    descfr = Column(Text, nullable=True)
    blocofr = Column(Text, nullable=True)
    seo_titulosp = Column(Text, nullable=True)
    seo_descsp = Column(Text, nullable=True)
    seo_titulofr = Column(Text, nullable=True)
    seo_descfr = Column(Text, nullable=True)
    nomede = Column(Text, nullable=True)
    descde = Column(Text, nullable=True)
    blocode = Column(Text, nullable=True)
    nomeit = Column(Text, nullable=True)
    descit = Column(Text, nullable=True)
    blocoit = Column(Text, nullable=True)
    combine_with = Column(Text, nullable=True)
    descritoressp = Column(Text, nullable=True)
    descritoresfr = Column(Text, nullable=True)
    descritoresde = Column(Text, nullable=True)
    descritoresit = Column(Text, nullable=True)
    seo_titulode = Column(Text, nullable=True)
    seo_descde = Column(Text, nullable=True)
    seo_tituloit = Column(Text, nullable=True)
    seo_descit = Column(Text, nullable=True)
    seo_meta = Column(Text, nullable=True)
    banner = Column(Boolean, nullable=True)
    grelha_tamanhos = Column(Integer, nullable=True)
    sales_unit = Column(Integer, nullable=True)
    package_type = Column(Integer, nullable=True)
    units_in_package = Column(Integer, nullable=True)
    nometec1_pt = Column(Text, nullable=True)
    nometec2_pt = Column(Text, nullable=True)
    nometec3_pt = Column(Text, nullable=True)
    nometec1_gb = Column(Text, nullable=True)
    nometec2_gb = Column(Text, nullable=True)
    nometec3_gb = Column(Text, nullable=True)
    nometec1_sp = Column(Text, nullable=True)
    nometec2_sp = Column(Text, nullable=True)
    nometec3_sp = Column(Text, nullable=True)
    nometec1_fr = Column(Text, nullable=True)
    nometec2_fr = Column(Text, nullable=True)
    nometec3_fr = Column(Text, nullable=True)
    nometec1_de = Column(Text, nullable=True)
    nometec2_de = Column(Text, nullable=True)
    nometec3_de = Column(Text, nullable=True)
    nometec1_it = Column(Text, nullable=True)
    nometec2_it = Column(Text, nullable=True)
    nometec3_it = Column(Text, nullable=True)
    weight = Column(Float, nullable=True)
    width = Column(Float, nullable=True)
    height = Column(Float, nullable=True)
    ean = Column(Text, nullable=True)
    ref_fabricante = Column(Text, nullable=True)
    keyfeature1pt = Column(Text, nullable=True)
    keyfeature2pt = Column(Text, nullable=True)
    keyfeature3pt = Column(Text, nullable=True)
    keyfeature4pt = Column(Text, nullable=True)
    keyfeature1gb = Column(Text, nullable=True)
    keyfeature2gb = Column(Text, nullable=True)
    keyfeature3gb = Column(Text, nullable=True)
    keyfeature4gb = Column(Text, nullable=True)
    keyfeature1sp = Column(Text, nullable=True)
    keyfeature2sp = Column(Text, nullable=True)
    keyfeature3sp = Column(Text, nullable=True)
    keyfeature4sp = Column(Text, nullable=True)
    keyfeature1fr = Column(Text, nullable=True)
    keyfeature2fr = Column(Text, nullable=True)
    keyfeature3fr = Column(Text, nullable=True)
    keyfeature4fr = Column(Text, nullable=True)
    keyfeature1de = Column(Text, nullable=True)
    keyfeature2de = Column(Text, nullable=True)
    keyfeature3de = Column(Text, nullable=True)
    keyfeature4de = Column(Text, nullable=True)
    keyfeature1it = Column(Text, nullable=True)
    keyfeature2it = Column(Text, nullable=True)
    keyfeature3it = Column(Text, nullable=True)
    keyfeature4it = Column(Text, nullable=True)
    garantiapt = Column(Text, nullable=True)
    garantiagb = Column(Text, nullable=True)
    garantiasp = Column(Text, nullable=True)
    garantiafr = Column(Text, nullable=True)
    garantiade = Column(Text, nullable=True)
    garantiait = Column(Text, nullable=True)
    unit_value = Column(Boolean, nullable=True)
    created_at = Column(DateTime(timezone=True), nullable=True)
    last_update = Column(DateTime, nullable=True)
    data_novidade = Column(DateTime, nullable=True)
    material = Column(Integer, nullable=True)
    info_shippingpt = Column(Text, nullable=True)
    info_shippinggb = Column(Text, nullable=True)
    info_shippingsp = Column(Text, nullable=True)
    info_shippingfr = Column(Text, nullable=True)
    info_shippingde = Column(Text, nullable=True)
    info_shippingit = Column(Text, nullable=True)
    variante = Column(Text, nullable=True)
    faqs = Column(Integer, nullable=True)
    descescala_met_pt = Column(Text, nullable=True)
    descescala_imp_pt = Column(Text, nullable=True)
    descescala_met_gb = Column(Text, nullable=True)
    descescala_imp_gb = Column(Text, nullable=True)
    descescala_met_sp = Column(Text, nullable=True)
    descescala_imp_sp = Column(Text, nullable=True)
    descescala_met_fr = Column(Text, nullable=True)
    descescala_imp_fr = Column(Text, nullable=True)
    descescala_met_de = Column(Text, nullable=True)
    descescala_imp_de = Column(Text, nullable=True)
    descescala_met_it = Column(Text, nullable=True)
    descescala_imp_it = Column(Text, nullable=True)
    generico4 = Column(Boolean, nullable=True)
    generico5 = Column(Boolean, nullable=True)
    generico29 = Column(Boolean, nullable=True)
    generico30 = Column(Boolean, nullable=True)
    servicos = Column(Text, nullable=True)
    PreparationTime = Column(Integer, nullable=True)
    ReplacementTime = Column(Integer, nullable=True)
    lenght = Column(Float, nullable=True)
    generico6 = Column(Text, nullable=True)
    generico7 = Column(Text, nullable=True)
    generico8 = Column(Text, nullable=True)
    generico9 = Column(Text, nullable=True)
    generico10 = Column(Text, nullable=True)
    generico11 = Column(Text, nullable=True)
    generico12 = Column(Text, nullable=True)
    generico13 = Column(Text, nullable=True)
    generico14 = Column(Text, nullable=True)
    generico15 = Column(Text, nullable=True)
    generico16 = Column(Text, nullable=True)
    generico17 = Column(Text, nullable=True)
    generico18 = Column(Text, nullable=True)
    generico19 = Column(Text, nullable=True)
    generico20 = Column(Text, nullable=True)
    generico21 = Column(Text, nullable=True)
    generico22 = Column(Text, nullable=True)
    generico23 = Column(Text, nullable=True)
    generico24 = Column(Text, nullable=True)
    generico25 = Column(Text, nullable=True)
    generico26 = Column(Text, nullable=True)
    generico27 = Column(Text, nullable=True)
    generico28 = Column(Text, nullable=True)
    composto = Column(Integer, nullable=True)
    marketplace_taxonomy_id = Column(Integer, nullable=True)
    marketplace_style_id = Column(Integer, nullable=True)
    marketplace_composition_id = Column(Integer, nullable=True)
    marketplace_color_id = Column(Integer, nullable=True)
    marketplace_size_id = Column(Integer, nullable=True)
    hs_code = Column(Integer, nullable=True)
    id_pais_origem = Column(Integer, nullable=True)
    data_novidade_ate = Column(DateTime, nullable=True)
    nomeus = Column(Text, nullable=True)
    nomenl = Column(Text, nullable=True)
    descus = Column(Text, nullable=True)
    descnl = Column(Text, nullable=True)
    blocous = Column(Text, nullable=True)
    bloconl = Column(Text, nullable=True)
    descritoresus = Column(Text, nullable=True)
    descritoresnl = Column(Text, nullable=True)
    seo_titulous = Column(Text, nullable=True)
    seo_titulonl = Column(Text, nullable=True)
    seo_descus = Column(Text, nullable=True)
    seo_descnl = Column(Text, nullable=True)
    nometec1_us = Column(Text, nullable=True)
    nometec1_nl = Column(Text, nullable=True)
    nometec2_us = Column(Text, nullable=True)
    nometec2_nl = Column(Text, nullable=True)
    nometec3_us = Column(Text, nullable=True)
    nometec3_nl = Column(Text, nullable=True)
    keyfeature1us = Column(Text, nullable=True)
    keyfeature1nl = Column(Text, nullable=True)
    keyfeature2us = Column(Text, nullable=True)
    keyfeature2nl = Column(Text, nullable=True)
    keyfeature3us = Column(Text, nullable=True)
    keyfeature3nl = Column(Text, nullable=True)
    keyfeature4us = Column(Text, nullable=True)
    keyfeature4nl = Column(Text, nullable=True)
    garantiaus = Column(Text, nullable=True)
    garantianl = Column(Text, nullable=True)
    info_shippingus = Column(Text, nullable=True)
    info_shippingnl = Column(Text, nullable=True)
    descescala_met_us = Column(Text, nullable=True)
    descescala_met_nl = Column(Text, nullable=True)
    descescala_imp_us = Column(Text, nullable=True)
    descescala_imp_nl = Column(Text, nullable=True)
    pos_armazem = Column(Text, nullable=True)
    last_remote_update = Column(DateTime, nullable=True)
    iva = Column(Integer, nullable=True)
    ProductDescriptionSaft = Column(Text, nullable=True)
    complement_with = Column(Text, nullable=True)
    feed_title_pt = Column(Text, nullable=True)
    feed_title_gb = Column(Text, nullable=True)
    feed_title_sp = Column(Text, nullable=True)
    feed_title_it = Column(Text, nullable=True)
    feed_title_de = Column(Text, nullable=True)
    feed_title_fr = Column(Text, nullable=True)
    feed_title_nl = Column(Text, nullable=True)
    feed_title_us = Column(Text, nullable=True)
    feed_desc_pt = Column(Text, nullable=True)
    feed_desc_gb = Column(Text, nullable=True)
    feed_desc_sp = Column(Text, nullable=True)
    feed_desc_it = Column(Text, nullable=True)
    feed_desc_de = Column(Text, nullable=True)
    feed_desc_fr = Column(Text, nullable=True)
    feed_desc_nl = Column(Text, nullable=True)
    feed_desc_us = Column(Text, nullable=True)
    data_disponibilidade_venda = Column(DateTime, nullable=True)
    data_entrada_armazem = Column(DateTime, nullable=True)
    codigo_amostra = Column(Integer, nullable=True)
    age_group = Column(Integer, nullable=True)
    classe_energetica = Column(Integer, nullable=True)
    stock = Column(Integer, nullable=True)
    pvp = Column(Float, nullable=True)
    pvpr = Column(Float, nullable=True)
